Add constituent tendency updater
ESCOMP/atmospheric_physics pull request #111
Opened 2024-08-22 22:53 UTC by peverwhee

Adds the `apply_constituent_tendencies` scheme to `utilties/physics_tendency_updaters.F90`.
- Replaces dadadj_apply_qv_tendency in the dadadj suite.

Testing:
- Confirmed no differences found with ne5 run of dadadj (compared to snapshots) on derecho

Waiting for a framework tag to enable new `constituent = True` metadata property.

2024-11-08 18:34 UTC, nusbaume requested changes
Looks good, but did have one request (which does expand the PR scope a little, sorry!).

Also just a reminder to update the missing standard names list when you get the chance.  Thanks!

2024-11-08 18:34 UTC, nusbaume commented on schemes/utilities/physics_tendency_updaters.F90
> +      const_tend = 0._kind_phys
I just realized that this zeroing out step is something we should probably do for the other tendency updaters too.  Could you possibly add it to them as well?

2024-11-09 16:06 UTC, nusbaume approved these changes
Looks great now, thanks!

2024-11-11 22:45 UTC, mwaxmonsky approved these changes
Looks great @peverwhee!

2024-11-27 19:07 UTC, merged