MUSICA TUVX scheme: create aerosol radiator, set_aerosol_optics_values
ESCOMP/atmospheric_physics pull request #182
Opened 2024-12-17 05:49 UTC by dwfncar

Added musica_ccpp_tuvx_aerosol_optics.F90 and test files.
set_aerosol_optics_values sets optical depths, etc to 0 for now ...

2024-12-18 17:53 UTC, dwfncar commented
See also https://github.com/NCAR/cam-sima-chemistry-data/pull/4

2025-01-07 15:53 UTC, K20shores approved these changes

2025-01-07 19:17 UTC, boulderdaze requested changes
Looks good! I just have a small request.

2025-01-07 19:17 UTC, boulderdaze commented on schemes/musica/tuvx/musica_ccpp_tuvx_aerosol_optics.F90
> +  function create_aerosol_optics_radiator( height_grid, wavelength_grid, &
Could you include descriptions for the function?

2025-01-07 19:17 UTC, boulderdaze commented on schemes/musica/tuvx/musica_ccpp_tuvx_aerosol_optics.F90
> +  subroutine set_aerosol_optics_values( radiator, &
Could you include descriptions for the function?

2025-01-08 23:45 UTC, mattldawson approved these changes
looks good! Just one minor suggestion

2025-01-08 23:45 UTC, mattldawson commented on schemes/musica/tuvx/musica_ccpp_tuvx_aerosol_optics.F90
> +  subroutine set_aerosol_optics_values( radiator, &
Could you also include in the description a note about this temporarily setting optical properties to zero until aerosol optical property calculations are ported to CAM-SIMA?

2025-01-09 20:26 UTC, jimmielin approved these changes
Thanks @dwfncar!

2025-01-09 20:39 UTC, boulderdaze approved these changes

2025-01-09 20:40 UTC, merged