101 calculate no photolysis rate constants
ESCOMP/atmospheric_physics pull request #183
Opened 2024-12-18 23:09 UTC by K20shores

Closes #101 

There are a number of TODOs I still need to figure out, and I'm not really sure how to test this properly. The [paper](https://doi.org/10.1029/93JD02007) detailing the implemented algorithm doesn't seem to list individual values for Js, and I'm not sure what values they used for their extra terrestrial flux, but that could be a potential testing avenue if we thinks its worth me tracking down values from references.

2024-12-18 23:14 UTC, jimmielin commented
Hi @K20shores could you change the base branch of this PR to `development`? It seems like a lot of the diffs unrelated to this PR are showing in the changed files.

I'm happy to review once the PR is out of draft. Thanks!

2025-01-07 02:36 UTC, boulderdaze requested changes

2025-02-07 22:56 UTC, K20shores commented
Right now there's a memory leak, but I found out that you can pair valgrind with gdb to identify leaks *as the process is running*.

1. Build the docker file 
    - From the top level `docker build -t atmo -f test/docker/Dockerfile.musica.no_install --build-arg CAM_SIMA_CHEMISTRY_DATA_TAG=add_molecular_weight .`
2. Run the container and setup valgrind to wait for gdb
    - `docker run --rm -it atmo`
    - `valgrind --vgdb=yes --vgdb-error=0 ./test_musica_api `
3. Grab the container id and execute a new shell in that container
    - `docker ps`, copy the ContainerID for the `atmo` image
    - Start a new shell in that container, `docker exec -it 677e9af20b5f /bin/bash`, replacing the ID with the one you copied
4. Start `gdb` and make it target the valgrind process
    - `gdb ./test_musica_api`
    - Then, in the prompt, bring up the text user interface
      - `tui enable`
    - Then, target the valgrind process
      - `target remote | vgdb`
    - `gdb` is now connected to a running valgrind process. You can set breakpoints as you wish, or just type `c`ontinue and gdb will pause whenever valgrind encounters and issue
    - I find it useful to place the two terminals side by side so that you can easily read the valgrind error message beside the source code displayed in gdb
    - Type `kill` within gdb to stop the valgrind process
    - You can inspect other options gdb now has from valgrind by typing `monitor help`
      - `monitor leak_check` will show what leaks exist where you are in the code right now if you're paused on a breakpoint

2025-06-17 16:19 UTC, closed without merging

2025-06-17 16:19 UTC, mattldawson commented
we can reopen this once NO photolysis is needed

2025-08-15 14:51 UTC, K20shores commented
I've moved this branch into my fork. This work will likely still be necessary but isn't required right now. Here it is for posterity: 
https://github.com/K20shores/atmospheric_physics/tree/101-calculate-no-photolysis-rate-constants