Complete Zhang McFarlane conversion to CCPP
ESCOMP/atmospheric_physics pull request #186
Opened 2024-12-24 20:19 UTC by cacraigucar

closes #66

2025-01-09 19:08 UTC, jimmielin requested changes
Thanks @cacraigucar, and congratulations on completing ZM 🎉!!!

I have minor, hopefully just formatting related changes. As mentioned in the chat I will avoid proposing large changes (e.g., moving the ZM namelist scheme) in this PR so it can be merged and I can propose the changes in another future PR.

I have tested building and running of Hack shallow convection with `cloud_fraction_fice` and `zm_conv_evap` and verified they are within roundoff (and bit-for-bit for history output), as well as (modified for shallow) the interstitial schemes for conv fluxes to/from general/deep.

2025-01-09 19:08 UTC, jimmielin commented on schemes/sima_diagnostics/zm_evap_tendency_diagnostics.F90
> +    call history_add_field ('ZMEIHEAT', 'Heating by ice and evaporation in ZM convection', 'lev', 'avg', 'W kg-1')
I don't quite recall what we settled on from the last conversation about history variables - it appears that the second argument passed to `history_add_field` here and below are long names instead of standard names (which are used in the other diagnostic schemes).

I did go through some of the Hack equivalents (note `CM` instead of `ZM` suffix) of these and had some standard names handy for your reference:
* `EVAPTCM` - `tendency_of_air_temperature_due_to_convective_evaporation_due_to_shallow_convection`
* `FZSNTCM` - `tendency_of_air_temperature_due_to_frozen_precipitation_production_due_to_shallow_convection`
* `EVSNTCM` - `tendency_of_air_temperature_due_to_evaporation_and_melting_of_frozen_precipitation_due_to_shallow_convection`
* `EVAPQCM` - `tendency_of_water_vapor_mixing_ratio_wrt_moist_air_and_condensed_water_due_to_convective_evaporation_due_to_shallow_convection`

so maybe the same could be used (but `_due_to_deep_convection` instead of `_due_to_shallow_convection`)

2025-01-09 19:08 UTC, jimmielin commented on schemes/sima_diagnostics/zm_momtran_tendency_diagnostics.F90
> +!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Perhaps this comment block about being a template could be removed?

2025-01-09 19:08 UTC, jimmielin commented on schemes/sima_diagnostics/zm_momtran_tendency_diagnostics.F90
> +    call history_add_field ('ZMMTT',  'T tendency - ZM convective momentum transport', 'lev',  'avg', 'K s-1')
It appears that here and below the second argument to `history_add_field` is also long names instead of standard names (as in other files)

2025-01-09 19:08 UTC, jimmielin commented on schemes/sima_diagnostics/zm_momtran_tendency_diagnostics.F90
> +      use ccpp_constituent_prop_mod, only: ccpp_constituent_prop_ptr_t
It appears that this `use` statement is unused, perhaps it could be removed?

2025-01-09 19:08 UTC, jimmielin commented on schemes/sima_diagnostics/zm_momtran_tendency_diagnostics.F90
> +      character(len=256) :: standard_name
It appears that `lengath`, `const_idx`, and `standard_name` here are unused and could be removed.

2025-01-09 19:08 UTC, jimmielin commented on schemes/sima_diagnostics/zm_tendency_diagnostics.F90
> +!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Perhaps this comment block about being a template could be removed.

2025-01-09 19:08 UTC, jimmielin commented on schemes/sima_diagnostics/zm_tendency_diagnostics.F90
> +    call history_add_field ('ZMDICE', 'Cloud ice tendency - Zhang-McFarlane convection', 'lev',  'avg', 'kg kg-1 s-1')
It appears that here and below the second argument to history_add_field is also long names instead of standard names (as in other files)

2025-01-09 19:08 UTC, jimmielin commented on schemes/sima_diagnostics/zm_tendency_diagnostics.F90
> +         write(0,*) ' const_idx=', const_idx, ' standard_name=',standard_name
Please note the debug statement.

2025-01-09 19:08 UTC, jimmielin commented on schemes/utilities/to_be_ccppized_temporary.F90
> +module to_be_ccppized_temporary
Perhaps a call to this has to be added to the CAM7 SDF as well which will use ZM?

2025-01-09 19:08 UTC, jimmielin commented on schemes/zhang_mcfarlane/zm_conv_convtran.F90
> +! ccpp_constituent_properties - standard name -- see chat
Perhaps this comment could be removed now that the standard name is set?

2025-01-09 19:08 UTC, jimmielin commented on schemes/zhang_mcfarlane/zm_conv_convtran.F90
> +!   use constituents,    only: cnst_get_type_byind
Perhaps these commented out code could be removed?

2025-01-09 19:08 UTC, jimmielin commented on suites/suite_zhang_mcfarlane.xml
> +       <scheme>zm_convr</scheme>
I'm not sure if this is within the scope of the PR, but maybe the calls to ZM need to be added to the corresponding locations in the CAM7 SDF as well.

2025-01-13 17:48 UTC, cacraigucar reviewed
I believe that I have addressed all of your comment, though I might have missed some.

2025-01-13 17:48 UTC, cacraigucar commented on schemes/zhang_mcfarlane/set_general_conv_fluxes_to_deep.F90
> +   real(kind_phys), intent(in) :: prdprec_gen(:,:)
Removed

2025-01-13 17:50 UTC, jimmielin commented on schemes/sima_diagnostics/zm_diagnostics.F90
> +      lengath = count(ideep > 0)
Sorry, I realized I didn't really point to which variable I was referring to as "this" variable. I meant `lengath` - but maybe the same comment about it being used elsewhere in ZM applies?

2025-01-13 18:04 UTC, jimmielin approved these changes
Thanks @cacraigucar for addressing my comments!

There are a few comments I left open to get @nusbaume and @peverwhee's input, about the history variables and inclusion of ZM in the CAM7 SDF. I've marked the other comments as resolved.

2025-01-13 18:04 UTC, cacraigucar commented on schemes/zhang_mcfarlane/zm_convr_namelist.xml
> +<entry id="zmconv_co_lnd">
done

2025-01-13 21:15 UTC, peverwhee requested changes
hooray! zm! a few (hopefully) small things!

note: i didn't review the code in `to_be_ccppized` since I assumed it was copied over from CAM...

also, reminder that you'll want to regenerate NamesNotInDictionary.txt after all the reviews are done.

2025-01-13 21:15 UTC, peverwhee commented on schemes/zhang_mcfarlane/zm_conv_evap.meta
> +  dependencies = ../../to_be_ccppized/wv_saturation.F90
question for @nusbaume as he reviews - since wv_saturation.F90 depends on other to_be_ccppized modules, should this dependency list include those modules? e.g.

```
dependencies = ../../to_be_ccppized/wv_saturation.F90,../../to_be_ccppized/error_messages.F90,../../to_be_ccppized/wv_sat_methods.F90,../../to_be_ccppized/namelist_utils.F90,../../to_be_ccppized/units.F90
```

Same is true for zm_conv.meta and to_be_ccppized_temporary.meta

2025-01-13 21:15 UTC, peverwhee commented on schemes/utilities/to_be_ccppized_temporary.meta
> +  type = scheme
i believe this scheme should have the following dependency:

```
dependencies = ../../to_be_ccppized/wv_saturation.F90
```

2025-01-14 23:26 UTC, cacraigucar reviewed
I believe I have addressed all of @peverwhee's comments, but I may have missed one

2025-01-16 17:21 UTC, peverwhee commented on schemes/zhang_mcfarlane/zm_conv_convtran.meta
> +  advected = true
Oops, should've clarified. `advected = true` is only for individual constituents (not the whole array). I imagine this "works" since you've tested it, but I'd remove this to avoid future confusion

2025-01-16 17:21 UTC, peverwhee commented on schemes/zhang_mcfarlane/zm_conv_evap.F90
>        end if
ok! I guess I'd like to be sure we haven't lost functionality with this PR? since there used to be a way to make old_snow=.false. (by passing in prdsnow)

2025-01-16 17:26 UTC, peverwhee requested changes
a couple lingering things

2025-01-16 17:26 UTC, peverwhee commented on schemes/zhang_mcfarlane/zm_convr.meta
> +  advected = true
looks like this one has "advected = true" twice

2025-01-16 17:26 UTC, peverwhee commented on schemes/sima_diagnostics/zm_diagnostics.meta
> +#  intent = in
this can be removed

2025-01-16 17:27 UTC, peverwhee commented
not sure why the comment isn't showing up, but also this comment - https://github.com/ESCOMP/atmospheric_physics/pull/186/files#r1918923205

2025-01-17 19:44 UTC, cacraigucar commented on schemes/sima_diagnostics/zm_diagnostics.meta
> +#  intent = in
done

2025-01-17 19:44 UTC, cacraigucar commented on schemes/zhang_mcfarlane/zm_convr.meta
> +  advected = true
I guess I was over zealous.  Removed one

2025-01-17 19:44 UTC, cacraigucar commented on schemes/zhang_mcfarlane/zm_conv_convtran.meta
> +  advected = true
removed advected from this location

2025-01-17 19:44 UTC, cacraigucar commented on suites/suite_zhang_mcfarlane.xml
> +       <scheme>zm_convr</scheme>
Added ZM to the CAM7 SDF

2025-01-17 19:44 UTC, cacraigucar commented on schemes/utilities/to_be_ccppized_temporary.F90
> +module to_be_ccppized_temporary
@nusbaume and @peverwhee  - What are your thoughts on adding this to the CAM7 SDF?  By the time the CAM7 SDF is complete, I think a line like this might be lost in SDF.   I'm not sure I'd like to add this to the SDF for this reason, but on the other hand, we might need it as a stopgap measure to get CAM7 running initially and we will most likely have forgotten about it?

2025-01-17 20:21 UTC, cacraigucar commented on schemes/zhang_mcfarlane/zm_conv_evap.F90
>        end if
How about we keep it "as-is" (A user can change the hardwired default in the code) and we open an issue?  Since Rich indicated it "might" be obsolete code, I don't think it warrants fixing now, just to possibly take out the code later.  I know science ZM mods may be coming along soon, so we could address this then.  By adopting this stance, we are unfortunately guaranteeing that this code is not the final answer, that a change one way or the other needs to be adopted.

2025-01-17 21:06 UTC, peverwhee commented on schemes/zhang_mcfarlane/zm_conv_evap.F90
>        end if
Looking into it more, it seems that old_snow was only switched when zmconv_microp was .true. (which is a nl field). I'm guessing y'all decided to cut out microp at some point? If so, i'm ok with leaving it as-is.

2025-01-17 21:11 UTC, peverwhee commented on schemes/utilities/to_be_ccppized_temporary.F90
> +module to_be_ccppized_temporary
I guess I'll vote for leaving it in. My hope is we will delete `to_be_ccppized_temporary.F90` when it's time, which will preclude us from accidentally leaving it in the SDF

2025-01-17 23:16 UTC, cacraigucar commented on schemes/utilities/to_be_ccppized_temporary.F90
> +module to_be_ccppized_temporary
As I thought about how to implement this in CAM7, I believe it already is inherently in the CAM7 SDF, though it is not called out by name.  I believe it was needed for the subsequent wv_sat_run which is used internally in one of the ZM routines.  For the reason why I needed to add this routine, I believe that the current ZM is calling this, though not explicitly in the SDF.  So I don't believe I need to do anything more, but please let me know if I misunderstood the request.

2025-01-17 23:31 UTC, nusbaume requested changes
Great work @cacraigucar!  I do have some change requests, but hopefully they are all minor (and of course please let me know if you have any concerns with anything I suggested).  Thanks!

2025-01-17 23:31 UTC, nusbaume commented on suites/suite_cam7.xml
> +
I believe we need to add another set of `check_energy` calls after the ZM block here:

```suggestion
    <!-- Check that energy and water changes match the boundary fluxes -->
    <scheme>check_energy_scaling</scheme>
    <scheme>check_energy_chng</scheme>
```

2025-01-17 23:31 UTC, nusbaume commented on doc/ChangeLog
> +Github PR URL:
Just adding a reminder to finish the `ChangeLog` or add the same info to the PR description before merging.

2025-01-22 23:32 UTC, jimmielin commented on suites/suite_cam7.xml
> +
Thanks @nusbaume, also wanted to add that before running the ZM scheme, the following should be called to zero the inputs to `check_energy_chng`:
```
<scheme>check_energy_zero_fluxes</scheme>
```

Some inputs need to be provided to `check_energy_chng` to actually check the energy changes match the boundary fluxes.

Based on `physpkg.F90` calls to check_energy_chng after `convect_deep_tend`:
```fortran
    ! Check energy integrals, including "reserved liquid"
    flx_cnd(:ncol) = prec_dp(:ncol) + rliq(:ncol)
    snow_dp(:ncol) = snow_dp(:ncol) + rice(:ncol)
    call check_energy_cam_chng(state, tend, "convect_deep", nstep, ztodt, zero, flx_cnd, snow_dp, zero)
    snow_dp(:ncol) = snow_dp(:ncol) - rice(:ncol)
```

the following inputs need to be provided (as an output from the ZM scheme):
* `scheme_name` = `"convect_deep"`
* `net_liquid_and_lwe_ice_fluxes_through_top_and_bottom_of_atmosphere_column` = `prec_dp(:ncol) + rliq(:ncol)`
* `net_lwe_ice_fluxes_through_top_and_bottom_of_atmosphere_column` = `snow_dp(:ncol) + rice(:ncol)`

2025-01-23 00:30 UTC, cacraigucar reviewed
@nusbaume - Let me know what you think about the few areas where I made some compromises and have questions for you.

2025-01-23 00:30 UTC, cacraigucar commented on suites/suite_zhang_mcfarlane.xml
> +<?xml version="1.0" encoding="UTF-8"?>
moved

2025-01-23 00:30 UTC, cacraigucar commented on suites/suite_cam7.xml
> +
@jimmielin - can we open this as a new issue?  I have converted ZM, and we can make convect_deep with its additional features a new PR?  I'm literally on my last edits and I want to avoid feature creep (and missing deadlines)

2025-01-23 00:30 UTC, cacraigucar commented on to_be_ccppized/units.F90
> +module units
removed

2025-01-23 03:34 UTC, jimmielin commented on suites/suite_zhang_mcfarlane.xml
> +       <scheme>zm_convr</scheme>
Thanks @cacraigucar !

2025-01-23 03:35 UTC, jimmielin commented on suites/suite_cam7.xml
> +
@cacraigucar agreed, I am happy to defer this to the future - I can work on this as an example of how `check_energy_chng` is called as I didn't have a good example to work with when I converted it.

Added issue https://github.com/ESCOMP/atmospheric_physics/issues/192

2025-01-23 04:01 UTC, peverwhee commented on schemes/utilities/to_be_ccppized_temporary.F90
> +module to_be_ccppized_temporary
If I remember correctly, you added the `to_be_ccppized_temporary` scheme to call `wv_sat_init`. Is that being called by a different scheme in the SDF? If not, we'll need it in the SDF or the call to `wv_sat_run` that's internal to ZM will fail.

2025-01-23 04:08 UTC, peverwhee approved these changes
thanks @cacraigucar !

2025-01-23 15:29 UTC, nusbaume commented on schemes/sima_diagnostics/zm_convr_tendency_diagnostics.F90
> +      call history_out_field('ZMDT    ', ftem)
I am fine to keep it for now, especially given that this is just a "nice to have" and we are obviously under time constraints.  The same holds for all the other `ftem` requests below, so I'll go ahead and mark them resolved.  Thanks!

2025-01-23 15:37 UTC, nusbaume commented on schemes/sima_diagnostics/zm_diagnostics.F90
> +      call history_out_field('CMFMC_DP', mconzm)
Looks like the `mconzm` variable declaration still needs to be removed as well (as it doesn't appear to be used anywhere else).

2025-01-23 15:48 UTC, nusbaume commented on schemes/zhang_mcfarlane/zm_conv_evap.F90
> +! convert from precip to kg/m2/s
I think this comment should  be:

```suggestion
! convert from 'kg m-2 s-1' to 'm s-1' using density of fresh water.
```

2025-01-23 15:48 UTC, nusbaume commented on to_be_ccppized/units.F90
> +module units
It looks like this file is still in the PR?

2025-01-23 15:49 UTC, nusbaume commented on suites/suite_zhang_mcfarlane.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Looks like this file still needs to be moved?

2025-01-23 15:50 UTC, nusbaume commented on suites/suite_cam7.xml
> +
This all sounds like a good plan to me!  I'm keeping this open so we can find it if need be, but feel free to consider it "resolved" for this PR.  Thanks!

2025-01-23 15:52 UTC, nusbaume requested changes
Getting much closer!  Just some missed changes from the previous review along with one comment change request.  Thanks!

2025-01-23 17:22 UTC, cacraigucar reviewed
I'd forgotten to push my last set of changes last night...  sigh.  Could you please resolve the issues that were in that push, so I can see what is left?  Also, I am still looking into the `to_be_ccppized_temporary`

2025-01-23 17:22 UTC, cacraigucar commented on schemes/zhang_mcfarlane/zm_conv_evap.F90
> +! convert from precip to kg/m2/s
added

2025-01-23 17:51 UTC, nusbaume requested changes
Almost there!  Just two missed requests from earlier.

2025-01-23 17:51 UTC, nusbaume commented on schemes/zhang_mcfarlane/zm_conv_evap.F90
> +! convert from 'kg m-2 s-1' to 'm s-1'
I really think we should emphasize that the `1000._kind_phys` below is the density of fresh water, as this technically has physical implications (as opposed to just a pure unit conversion).

2025-01-23 17:51 UTC, nusbaume commented on schemes/sima_diagnostics/zm_diagnostics.F90
> +      real(kind_phys) :: mconzm(ncol,pverp)
This variable (`mconzm`) is no longer used.

2025-01-23 18:44 UTC, cacraigucar reviewed
Next try - there are still some unresolved conversations, but they are for things I remember doing, so I think they are in there.

2025-01-23 18:44 UTC, cacraigucar commented on schemes/utilities/to_be_ccppized_temporary.F90
> +module to_be_ccppized_temporary
Well, it turns out that it is at the top of both the `suite_zhang_mcfarlane.xml` as well as the top of the ZM section in the CAM7 suite.  So it is being tested - I just missed seeing it in my scanning of the files.

2025-01-23 18:44 UTC, cacraigucar commented on schemes/sima_diagnostics/zm_diagnostics.F90
> +      real(kind_phys) :: mconzm(ncol,pverp)
removed

2025-01-23 18:44 UTC, cacraigucar commented on schemes/zhang_mcfarlane/zm_conv_evap.F90
> +! convert from 'kg m-2 s-1' to 'm s-1'
good point - I put in a variable for it.

2025-01-24 22:08 UTC, merged