ZM clean up round 2
ESCOMP/atmospheric_physics pull request #88
Opened 2024-03-13 22:26 UTC by cacraigucar

More cleanup identified during CCPP standard name meetings

Includes preliminary metadata for ZM (ignore for now as I know it is not complete - next review should include the entire files)

Closes #83

2024-03-15 22:54 UTC, cacraigucar commented on zhang_mcfarlane/zm_conv_momtran.F90
> +   real(kind_phys),intent(out) ::  icwd(:,:,:)      ! In-cloud winds in downdraft         ! (ncol,pver,2)
Neglected to separate these into two - need to do this

2024-03-18 19:46 UTC, cacraigucar commented on zhang_mcfarlane/zm_conv_momtran.F90
> +   real(kind_phys),intent(out) ::  icwd(:,:,:)      ! In-cloud winds in downdraft         ! (ncol,pver,2)
This has now been done

2024-04-02 15:59 UTC, nusbaume requested changes
Looks good!  Just a few changes requested in the momtran code.

Also I didn't review the metadata files, but if you would like me to at this stage please let me know.  Thanks!

2024-04-02 15:59 UTC, nusbaume commented on zhang_mcfarlane/zm_conv_momtran.F90
> +   real(kind_phys),intent(out) ::  pgdallv(:,:)      ! Apparent force from  downdraft PG V winds! (ncol,pver)
Not to be grammar-obsessed, but:

```suggestion
   real(kind_phys),intent(out) ::  pguallu(:,:)      ! Apparent force from  updraft PG on U winds  ! (ncol,pver)
   real(kind_phys),intent(out) ::  pguallv(:,:)      ! Apparent force from  updraft PG on V winds  ! (ncol,pver)
   real(kind_phys),intent(out) ::  pgdallu(:,:)      ! Apparent force from  downdraft PG on U winds! (ncol,pver)
   real(kind_phys),intent(out) ::  pgdallv(:,:)      ! Apparent force from  downdraft PG  on V winds! (ncol,pver)
```

2024-04-02 15:59 UTC, nusbaume commented on zhang_mcfarlane/zm_conv_momtran.F90
> +   real(kind_phys) :: pgdall(ncol,pver,num_winds)      ! Combined apparent force from  downdraft PG U winds
Comment grammar:

```suggestion
   real(kind_phys) :: pguall(ncol,pver,num_winds)      ! Combined apparent force from  updraft PG  on winds
   real(kind_phys) :: pgdall(ncol,pver,num_winds)      ! Combined apparent force from  downdraft PG on winds
```

2024-04-02 15:59 UTC, nusbaume commented on zhang_mcfarlane/zm_conv_momtran.F90
> +   icwuu(:ncol,:)       = icwu(:,:,1)
I think this needs to be:

```suggestion
   icwuv(:ncol,:)       = icwu(:,:,2)
```

2024-04-15 20:40 UTC, cacraigucar commented on zhang_mcfarlane/zm_conv_momtran.F90
> +   real(kind_phys),intent(out) ::  pgdallv(:,:)      ! Apparent force from  downdraft PG V winds! (ncol,pver)
fixed

2024-04-15 20:40 UTC, cacraigucar commented on zhang_mcfarlane/zm_conv_momtran.F90
> +   real(kind_phys) :: pgdall(ncol,pver,num_winds)      ! Combined apparent force from  downdraft PG U winds
fixed - bonus fix - corrected "comibined" a right below

2024-04-15 20:40 UTC, cacraigucar commented on zhang_mcfarlane/zm_conv_momtran.F90
> +   icwuu(:ncol,:)       = icwu(:,:,1)
good catch!

2024-04-16 20:11 UTC, nusbaume approved these changes
I have one last comment change request, but it doesn't require a re-review.  Otherwise everything looks great now, thanks!

2024-04-16 20:11 UTC, nusbaume commented on zhang_mcfarlane/zm_conv_momtran.F90
> +   real(kind_phys) :: pgdall(ncol,pver,num_winds)      ! Combined apparent force from  downdraft on PG U winds
I think `on` should be after `PG` here:

```suggestion
   real(kind_phys) :: pguall(ncol,pver,num_winds)      ! Combined apparent force from  updraft PG on U winds
   real(kind_phys) :: pgdall(ncol,pver,num_winds)      ! Combined apparent force from  downdraft PG on U winds
```

2024-04-16 22:17 UTC, merged