Implementation of CCPP-ized TJ2016
ESCOMP/atmospheric_physics pull request #92
Opened 2024-05-07 00:24 UTC by mwaxmonsky

Implements TJ2016 schemes using CCPP-ized metadata files.

Updates the design of the `run` functions to pass in state data and output tendencies (instead of modifying state directly) and changes those to be applied afterwards via additional `apply_*` schemes listed in order in the suite definition file.

Also updates ZM/Kessler variables using the `gravitational_acceleration` standard name to `standard_gravitational_acceleration` as these are needed by changes that are being made to CAM-SIMA standard names in a simultaneous PR there (to match recent discussions about that particular standard name).

2024-05-16 18:07 UTC, nusbaume requested changes
Thanks for all the hard work in getting this through @mwaxmonsky!  I do have some change requests, but hopefully all of them are fairly minor.  Of course if you have any questions or concerns with any of my requests just let me know!

2024-05-17 18:43 UTC, mwaxmonsky commented on kessler/kessler_update.meta
> +  standard_name = standard_ravitational_acceleration
Good catch!  Fixed!

2024-05-17 18:43 UTC, mwaxmonsky commented on tj2016/suite_tj2016_precip.xml
> +</suite>
Moved!

2024-05-17 18:43 UTC, mwaxmonsky commented on tj2016/suite_tj2016_sfc_pbl_hs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Moved!

2024-05-17 18:43 UTC, mwaxmonsky commented on tj2016/tj2016_precip.F90
> +    use shr_const_mod, only: pi => shr_const_pi
Removed and updated meta.

2024-05-17 18:44 UTC, mwaxmonsky commented on tj2016/tj2016_precip.F90
> +CONTAINS
Lowercased!

2024-05-17 18:44 UTC, mwaxmonsky commented on tj2016/tj2016_precip.F90
> +        real(kind_phys), intent(in)    :: cappa       ! Rd/cp
Removed!  It's only used in `sfc_pbl_hs` so I must have copied it into both without looking closer.

2024-05-17 18:44 UTC, mwaxmonsky commented on tj2016/tj2016_precip.F90
> +        real(kind_phys), intent(in)    :: epsilo      ! Rd/Rv: ratio of h2o to dry air molecular weights
Removed!

2024-05-17 18:45 UTC, mwaxmonsky commented on tj2016/tj2016_precip.F90
> +        real(kind_phys), intent(out)   :: precl(:)             ! large-scale precipitation rate (m/s)
Cleaned up!

2024-05-17 18:46 UTC, mwaxmonsky commented on tj2016/tj2016_precip.meta
> +  standard_name = ratio_of_h2o_to_dry_air_molecular_weights
Updated!

2024-05-17 18:46 UTC, mwaxmonsky commented on tj2016/tj2016_precip.meta
> +  units = 1
Updated!

2024-05-17 18:46 UTC, mwaxmonsky commented on tj2016/tj2016_precip.meta
> +  standard_name = stratiform_precipitation_rate
Updated!

2024-05-17 18:46 UTC, mwaxmonsky commented on tj2016/tj2016_sfc_pbl_hs.F90
> +    use shr_const_mod, only: pi => shr_const_pi
Removed and updated API And meta.

2024-05-17 18:46 UTC, mwaxmonsky commented on tj2016/tj2016_sfc_pbl_hs.F90
> +CONTAINS
Lowercased!

2024-05-17 18:46 UTC, mwaxmonsky commented on tj2016/tj2016_sfc_pbl_hs.F90
> +    real(kind_phys), intent(in)    :: cappa               ! Rd/cp
Updated!

2024-05-17 18:46 UTC, mwaxmonsky commented on tj2016/tj2016_sfc_pbl_hs.F90
> +    real(kind_phys), intent(in)    :: zvirv(:,:)          ! (rh2o/rair) - 1, needed for virtual temperaturr
Corrected!

2024-05-17 18:49 UTC, mwaxmonsky commented on tj2016/tj2016_sfc_pbl_hs.meta
> +  standard_name = ratio_of_h2o_to_dry_air_molecular_weights
Fixed!

2024-05-17 18:49 UTC, mwaxmonsky commented on tj2016/tj2016_sfc_pbl_hs.meta
> +  intent = out
Changed!

2024-05-17 19:11 UTC, mwaxmonsky commented on tj2016/tj2016_precip.meta
> +  intent = out
Added!

2024-06-15 20:39 UTC, nusbaume commented on tj2016/tj2016_sfc_pbl_hs.meta
> +  standard_name = surface_upward_latent_heat_flux
@mwaxmonsky Looking at the updated spreadsheet it appears that the standard name for `lhflx` is correct as-is, but the standard name for `shflx` should be just `surface_upward_sensible_heat_flux`.  So if we could drop the `for_coupling` from the `shflx` standard name that would be ideal.  Thanks!

2024-06-17 14:08 UTC, mwaxmonsky commented on tj2016/tj2016_sfc_pbl_hs.meta
> +  standard_name = surface_upward_latent_heat_flux
Updated!

2024-06-18 20:10 UTC, peverwhee approved these changes
looks good to me!

2024-06-24 03:38 UTC, merged